name: voila
channels:
  - conda-forge
dependencies:
  - jupyterlab=3
  - ipyvolume
  - bqplot
  - scipy
  - ipympl
  - voila=0.2.7
  - ipympl
  - xleaflet=0.11.1
  - xeus-cling>=0.12
  - requests
  - ipywidgets
  - geocoder
  - mapboxgl-notebook
  - shapely
  - geojson
  - tqdm
  - beautifulsoup4